<?php

namespace Codifyo\TsGeneratorBundle\Tests\Helper;

use Codifyo\TsGeneratorBundle\Converter\PhpToTypeScriptTypeConverter;
use Codifyo\TsGeneratorBundle\Extractor\SymfonySerializerRuntimeExtractor;
use Codifyo\TsGeneratorBundle\Generator\TypeScriptGenerator;
use Codifyo\TsGeneratorBundle\Helper\ClassResolver;
use Codifyo\TsGeneratorBundle\Tests\Fixtures\DummyEntityWithUseImport;

use Codifyo\TsGeneratorBundle\Tests\Fixtures\SubNamespace\DummyImportedEntity;
use Codifyo\TsGeneratorBundle\Writer\FileWriter;
use PHPUnit\Framework\TestCase;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\Serializer\Mapping\Factory\ClassMetadataFactory;
use Symfony\Component\Serializer\Mapping\Loader\AttributeLoader;
use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;
use Symfony\Component\Serializer\Serializer;

class ClassResolverTest extends TestCase
{
    private string $tempDir;

    protected function setUp(): void
    {
        $this->tempDir = sys_get_temp_dir() . '/ts_class_resolver_test_' . uniqid();
    }

    protected function tearDown(): void
    {
        $filesystem = new Filesystem();
        if ($filesystem->exists($this->tempDir)) {
            $filesystem->remove($this->tempDir);
        }
    }

    public function testResolveFqcnWithUseStatement(): void
    {
        $reflection = new \ReflectionClass(DummyEntityWithUseImport::class);
        $resolved = ClassResolver::resolveFqcn('DummyImportedEntity', $reflection);

        $this->assertEquals(DummyImportedEntity::class, $resolved);
    }

    public function testAutoGenerateDepsWithCrossNamespaceUseImport(): void
    {
        $classMetadataFactory = new ClassMetadataFactory(new AttributeLoader());
        $normalizer = new ObjectNormalizer($classMetadataFactory);
        $serializer = new Serializer([$normalizer]);

        $converter = new PhpToTypeScriptTypeConverter();
        $extractor = new SymfonySerializerRuntimeExtractor($serializer, null, $converter, $classMetadataFactory);
        $fileWriter = new FileWriter(new Filesystem(), $this->tempDir);

        $projectsConfig = [
            'projet1' => [
                'dir' => $this->tempDir,
                'types' => [
                    [
                        'class' => DummyEntityWithUseImport::class,
                        'groups' => ['serializer_group'],
                        'auto_generate_deps' => true,
                    ],
                ],
            ],
        ];

        $generator = new TypeScriptGenerator($extractor, $fileWriter, $projectsConfig);
        $results = $generator->generate('projet1');

        $this->assertCount(2, $results['projet1']);
        $this->assertFileExists($this->tempDir . '/DummyEntityWithUseImport.ts');
        $this->assertFileExists($this->tempDir . '/DummyImportedEntity.ts');

        $mainContent = file_get_contents($this->tempDir . '/DummyEntityWithUseImport.ts');
        $this->assertStringContainsString("import { DummyImportedEntity } from './DummyImportedEntity';", $mainContent);
        $this->assertStringContainsString("importedItems: Array<DummyImportedEntity>;", $mainContent);
    }
}
