<?php

namespace Codifyo\TsGeneratorBundle\Model;

class TypeConfig
{
    /**
     * @param string[] $groups
     */
    public function __construct(
        private string $class,
        private array $groups = [],
        private ?string $name = null,
        private string $kind = 'interface',
        private bool $autoGenerateDeps = false,
        private ?string $mode = null
    ) {
    }

    public function getClass(): string
    {
        return $this->class;
    }

    /**
     * @return string[]
     */
    public function getGroups(): array
    {
        return $this->groups;
    }

    public function getName(): string
    {
        if ($this->name !== null && $this->name !== '') {
            return $this->name;
        }

        $parts = explode('\\', $this->class);

        return end($parts);
    }

    public function getKind(): string
    {
        return in_array(strtolower($this->kind), ['interface', 'class', 'type'], true)
            ? strtolower($this->kind)
            : 'interface';
    }

    public function isAutoGenerateDeps(): bool
    {
        return $this->autoGenerateDeps;
    }

    public function getMode(): ?string
    {
        if ($this->mode === null || $this->mode === '') {
            return null;
        }

        $normalized = strtolower($this->mode);

        return in_array($normalized, ['auto', 'runtime', 'static', 'jms'], true) ? $normalized : 'auto';
    }
}
