<?php

namespace Codifyo\TsGeneratorBundle\Tests\Generator;

use Codifyo\TsGeneratorBundle\Converter\PhpToTypeScriptTypeConverter;
use Codifyo\TsGeneratorBundle\Extractor\SymfonySerializerRuntimeExtractor;
use Codifyo\TsGeneratorBundle\Generator\TypeScriptGenerator;
use Codifyo\TsGeneratorBundle\Tests\Fixtures\DummyPostWithRelation;
use Codifyo\TsGeneratorBundle\Writer\FileWriter;
use PHPUnit\Framework\TestCase;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\Serializer\Mapping\Factory\ClassMetadataFactory;
use Symfony\Component\Serializer\Mapping\Loader\AttributeLoader;
use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;
use Symfony\Component\Serializer\Serializer;

class AutoDepsAndInlineTest extends TestCase
{
    private string $tempDir;

    protected function setUp(): void
    {
        $this->tempDir = sys_get_temp_dir() . '/ts_autodeps_test_' . uniqid();
    }

    protected function tearDown(): void
    {
        $filesystem = new Filesystem();
        if ($filesystem->exists($this->tempDir)) {
            $filesystem->remove($this->tempDir);
        }
    }

    public function testWithAutoGenerateDepsTrue(): void
    {
        $classMetadataFactory = new ClassMetadataFactory(new AttributeLoader());
        $normalizer = new ObjectNormalizer($classMetadataFactory);
        $serializer = new Serializer([$normalizer]);

        $converter = new PhpToTypeScriptTypeConverter();
        $extractor = new SymfonySerializerRuntimeExtractor($serializer, null, $converter, $classMetadataFactory);
        $fileWriter = new FileWriter(new Filesystem(), $this->tempDir);

        $projectsConfig = [
            'projet1' => [
                'dir' => $this->tempDir,
                'types' => [
                    [
                        'class' => DummyPostWithRelation::class,
                        'groups' => ['serializer_group'],
                        'auto_generate_deps' => true,
                    ],
                ],
            ],
        ];

        $generator = new TypeScriptGenerator($extractor, $fileWriter, $projectsConfig);
        $results = $generator->generate('projet1');

        $this->assertCount(2, $results['projet1']);
        $this->assertFileExists($this->tempDir . '/DummyPostWithRelation.ts');
        $this->assertFileExists($this->tempDir . '/DummyTag.ts');

        $postContent = file_get_contents($this->tempDir . '/DummyPostWithRelation.ts');
        $this->assertStringContainsString("import { DummyTag } from './DummyTag';", $postContent);
        $this->assertStringContainsString("tags: Array<DummyTag>;", $postContent);
        $this->assertStringNotContainsString("tags?:", $postContent);
    }

    public function testWithAutoGenerateDepsFalseRendersInline(): void
    {
        $classMetadataFactory = new ClassMetadataFactory(new AttributeLoader());
        $normalizer = new ObjectNormalizer($classMetadataFactory);
        $serializer = new Serializer([$normalizer]);

        $converter = new PhpToTypeScriptTypeConverter();
        $extractor = new SymfonySerializerRuntimeExtractor($serializer, null, $converter, $classMetadataFactory);
        $fileWriter = new FileWriter(new Filesystem(), $this->tempDir);

        $projectsConfig = [
            'projet1' => [
                'dir' => $this->tempDir,
                'types' => [
                    [
                        'class' => DummyPostWithRelation::class,
                        'groups' => ['serializer_group'],
                        'auto_generate_deps' => false,
                    ],
                ],
            ],
        ];

        $generator = new TypeScriptGenerator($extractor, $fileWriter, $projectsConfig);
        $results = $generator->generate('projet1');

        $this->assertCount(1, $results['projet1']);
        $this->assertFileExists($this->tempDir . '/DummyPostWithRelation.ts');
        $this->assertFileDoesNotExist($this->tempDir . '/DummyTag.ts');

        $postContent = file_get_contents($this->tempDir . '/DummyPostWithRelation.ts');
        $this->assertStringNotContainsString("import { DummyTag }", $postContent);
        $this->assertStringContainsString("tags: Array<{ id: number; label: string }>;", $postContent);
        $this->assertStringNotContainsString("tags?:", $postContent);
    }
}
