<?php

namespace Codifyo\TsGeneratorBundle\Tests\Generator;

use Codifyo\TsGeneratorBundle\Converter\PhpToTypeScriptTypeConverter;
use Codifyo\TsGeneratorBundle\Extractor\SymfonySerializerMetadataExtractor;
use Codifyo\TsGeneratorBundle\Generator\TypeScriptGenerator;
use Codifyo\TsGeneratorBundle\Tests\Fixtures\DummyRole;
use Codifyo\TsGeneratorBundle\Tests\Fixtures\DummyUser;
use Codifyo\TsGeneratorBundle\Writer\FileWriter;
use PHPUnit\Framework\TestCase;
use Symfony\Component\Filesystem\Filesystem;

class TypeScriptGeneratorTest extends TestCase
{
    private string $tempDir;

    protected function setUp(): void
    {
        $this->tempDir = sys_get_temp_dir() . '/ts_generator_test_' . uniqid();
    }

    protected function tearDown(): void
    {
        $filesystem = new Filesystem();
        if ($filesystem->exists($this->tempDir)) {
            $filesystem->remove($this->tempDir);
        }
    }

    public function testGenerateProjectFilesWithInterfaceKind(): void
    {
        $converter = new PhpToTypeScriptTypeConverter();
        $extractor = new SymfonySerializerMetadataExtractor(null, null, $converter);
        $fileWriter = new FileWriter(new Filesystem(), $this->tempDir);

        $projectsConfig = [
            'projet1' => [
                'dir' => $this->tempDir,
                'types' => [
                    ['class' => DummyUser::class, 'groups' => ['serializer_group'], 'kind' => 'interface'],
                    ['class' => DummyRole::class, 'groups' => ['serializer_group'], 'kind' => 'interface'],
                ],
            ],
        ];

        $generator = new TypeScriptGenerator($extractor, $fileWriter, $projectsConfig);
        $results = $generator->generate('projet1');

        $this->assertArrayHasKey('projet1', $results);
        $this->assertCount(2, $results['projet1']);

        $userTsFile = $this->tempDir . DIRECTORY_SEPARATOR . 'DummyUser.ts';
        $userContent = file_get_contents($userTsFile);

        $this->assertStringContainsString('export interface DummyUser {', $userContent);
        $this->assertStringContainsString('id: number;', $userContent);
        $this->assertStringContainsString('username: string;', $userContent);
        $this->assertStringContainsString("import { DummyRole } from './DummyRole';", $userContent);
    }

    public function testGenerateProjectFilesWithClassKind(): void
    {
        $converter = new PhpToTypeScriptTypeConverter();
        $extractor = new SymfonySerializerMetadataExtractor(null, null, $converter);
        $fileWriter = new FileWriter(new Filesystem(), $this->tempDir);

        $projectsConfig = [
            'projet1' => [
                'dir' => $this->tempDir,
                'types' => [
                    ['class' => DummyUser::class, 'groups' => ['serializer_group'], 'kind' => 'class'],
                ],
            ],
        ];

        $generator = new TypeScriptGenerator($extractor, $fileWriter, $projectsConfig);
        $results = $generator->generate('projet1');

        $userTsFile = $this->tempDir . DIRECTORY_SEPARATOR . 'DummyUser.ts';
        $userContent = file_get_contents($userTsFile);

        $this->assertStringContainsString('export class DummyUser {', $userContent);
    }

    public function testGenerateProjectFilesWithAutoGenerateDeps(): void
    {
        $converter = new PhpToTypeScriptTypeConverter();
        $extractor = new SymfonySerializerMetadataExtractor(null, null, $converter);
        $fileWriter = new FileWriter(new Filesystem(), $this->tempDir);

        // Only register DummyUser, but enable auto_generate_deps
        $projectsConfig = [
            'projet1' => [
                'dir' => $this->tempDir,
                'types' => [
                    ['class' => DummyUser::class, 'groups' => ['serializer_group'], 'kind' => 'interface', 'auto_generate_deps' => true],
                ],
            ],
        ];

        $generator = new TypeScriptGenerator($extractor, $fileWriter, $projectsConfig);
        $results = $generator->generate('projet1');

        $roleTsFile = $this->tempDir . DIRECTORY_SEPARATOR . 'DummyRole.ts';
        $this->assertFileExists($roleTsFile);
        $roleContent = file_get_contents($roleTsFile);
        $this->assertStringContainsString('export interface DummyRole {', $roleContent);
    }
}
