<?php

namespace Codifyo\TsGeneratorBundle\Generator;

use Codifyo\TsGeneratorBundle\Extractor\MetadataExtractorInterface;
use Codifyo\TsGeneratorBundle\Model\ProjectConfig;
use Codifyo\TsGeneratorBundle\Model\TypeConfig;
use Codifyo\TsGeneratorBundle\Model\TypeDefinition;
use Codifyo\TsGeneratorBundle\Writer\FileWriter;

class TypeScriptGenerator implements TypeScriptGeneratorInterface
{
    /**
     * @param array<string, mixed> $projectsConfig
     */
    public function __construct(
        private MetadataExtractorInterface $extractor,
        private FileWriter $fileWriter,
        private array $projectsConfig = []
    ) {
    }

    public function generate(?string $projectName = null): array
    {
        $projects = $this->parseProjectsConfig();

        if ($projectName !== null && $projectName !== '') {
            if (!isset($projects[$projectName])) {
                throw new \InvalidArgumentException(sprintf('Project "%s" is not configured.', $projectName));
            }
            $projectsToProcess = [$projectName => $projects[$projectName]];
        } else {
            $projectsToProcess = $projects;
        }

        $results = [];

        foreach ($projectsToProcess as $name => $projectConfig) {
            $results[$name] = $this->generateProject($projectConfig);
        }

        return $results;
    }

    /**
     * @return array<string, ProjectConfig>
     */
    private function parseProjectsConfig(): array
    {
        $parsed = [];

        foreach ($this->projectsConfig as $name => $data) {
            $dir = $data['dir'] ?? 'public/ts/types';
            $projectMode = $data['mode'] ?? 'auto';
            $types = [];

            if (isset($data['types']) && is_array($data['types'])) {
                foreach ($data['types'] as $typeData) {
                    $class = $typeData['class'] ?? '';
                    $groups = $typeData['groups'] ?? [];
                    $customName = $typeData['name'] ?? null;
                    $kind = $typeData['kind'] ?? 'interface';
                    $autoGenerateDeps = (bool)($typeData['auto_generate_deps'] ?? false);
                    $typeMode = $typeData['mode'] ?? null;

                    if (!empty($class)) {
                        $types[] = new TypeConfig($class, $groups, $customName, $kind, $autoGenerateDeps, $typeMode);
                    }
                }
            }

            $parsed[$name] = new ProjectConfig($name, $dir, $types, $projectMode);
        }

        return $parsed;
    }

    /**
     * @return string[] List of written file paths
     */
    private function generateProject(ProjectConfig $projectConfig): array
    {
        $writtenFiles = [];
        $typeConfigs = $projectConfig->getTypes();

        // Index of already queued classes to avoid duplicate generation
        $processedClasses = [];
        foreach ($typeConfigs as $tc) {
            $processedClasses[$tc->getClass()] = true;
        }

        // Queue-based processing to allow auto-generation of dependent types
        $queue = array_values($typeConfigs);
        $generatedTypeDefinitions = [];

        while (!empty($queue)) {
            /** @var TypeConfig $currentTypeConfig */
            $currentTypeConfig = array_shift($queue);
            if ($this->extractor instanceof ChainMetadataExtractor) {
                $typeDefinition = $this->extractor->extract($currentTypeConfig, $projectConfig->getMode());
            } else {
                $typeDefinition = $this->extractor->extract($currentTypeConfig);
            }
            $generatedTypeDefinitions[$currentTypeConfig->getClass()] = $typeDefinition;

            // Auto-generate dependencies if option enabled
            if ($currentTypeConfig->isAutoGenerateDeps()) {
                foreach ($typeDefinition->getImports() as $alias => $targetClass) {
                    if (!isset($processedClasses[$targetClass]) && class_exists($targetClass)) {
                        $processedClasses[$targetClass] = true;
                        $depTypeConfig = new TypeConfig(
                            $targetClass,
                            $currentTypeConfig->getGroups(),
                            null,
                            $currentTypeConfig->getKind(),
                            true
                        );
                        $queue[] = $depTypeConfig;
                    }
                }
            }
        }

        // Map of FQCN => TS Type Name
        $generatedTypeNames = [];
        foreach ($generatedTypeDefinitions as $fqcn => $def) {
            $generatedTypeNames[$fqcn] = $def->getName();
        }

        foreach ($generatedTypeDefinitions as $fqcn => $typeDefinition) {
            $content = $this->renderTypeDefinition($typeDefinition, $generatedTypeNames);
            $fileName = $typeDefinition->getName() . '.ts';
            $filePath = $this->fileWriter->writeFile($projectConfig->getDir(), $fileName, $content);
            $writtenFiles[] = $filePath;
        }

        return $writtenFiles;
    }

    /**
     * @param array<string, string> $generatedTypeNames Map of FQCN => TS Type Name in project
     */
    private function renderTypeDefinition(TypeDefinition $definition, array $generatedTypeNames): string
    {
        $lines = [];
        $lines[] = '/* tslint:disable */';
        $lines[] = '/* eslint-disable */';
        $lines[] = '// Auto-generated by CodifyoTsGeneratorBundle. Do not edit manually.';
        $lines[] = '';

        // Handle Imports
        $imports = [];
        foreach ($definition->getImports() as $alias => $targetClass) {
            if (isset($generatedTypeNames[$targetClass]) && $targetClass !== $definition->getClassName()) {
                $targetTsName = $generatedTypeNames[$targetClass];
                $imports[] = sprintf("import { %s } from './%s';", $targetTsName, $targetTsName);
            }
        }

        if (!empty($imports)) {
            foreach (array_unique($imports) as $importLine) {
                $lines[] = $importLine;
            }
            $lines[] = '';
        }

        $kind = strtolower($definition->getKind());

        if ($kind === 'class') {
            $lines[] = sprintf('export class %s {', $definition->getName());
        } elseif ($kind === 'type') {
            $lines[] = sprintf('export type %s = {', $definition->getName());
        } else {
            $lines[] = sprintf('export interface %s {', $definition->getName());
        }

        foreach ($definition->getProperties() as $prop) {
            $propName = $prop->getName();
            $tsType = $prop->getTsType();

            if ($prop->getReferencedClass() !== null && isset($generatedTypeNames[$prop->getReferencedClass()])) {
                $targetTsName = $generatedTypeNames[$prop->getReferencedClass()];
                $refClass = $prop->getReferencedClass();
                $shortClass = (new \ReflectionClass($refClass))->getShortName();
                $tsType = str_replace($shortClass, $targetTsName, $tsType);
            }

            if ($prop->isNullable()) {
                $lines[] = sprintf('  %s?: %s | null;', $propName, $tsType);
            } else {
                $lines[] = sprintf('  %s: %s;', $propName, $tsType);
            }
        }

        if ($kind === 'type') {
            $lines[] = '};';
        } else {
            $lines[] = '}';
        }
        $lines[] = '';

        return implode("\n", $lines);
    }
}
